name = "SuperVFM"
uuid = "2bd08867-fde5-4212-94c3-7727a5759a5e"
authors = ["Piotr Stasiak <p.stasiak@newcastle.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
